"""
SPARK — Intervention Service
Determines appropriate intervention levels and manages intervention lifecycle.

Intervention Ladder:
Level 0: Passive monitoring (risk < 30%)
Level 1: Gentle contextual suggestions (30-50%)
Level 2: Momentum assistance (50-65%)
Level 3: Active collaboration (65-80%)
Level 4: Critical intervention (80-90%)
Level 5: Recovery mode (90-100%)
"""

from datetime import datetime, timezone
from typing import Optional

from app.core.logging import get_logger
from app.models.task import Task
from app.models.intervention import Intervention
from app.repositories.intervention_repository import InterventionRepository

logger = get_logger(__name__)


class InterventionService:
    """Manages the Adaptive Intervention System."""

    def __init__(self) -> None:
        self._intervention_repo = InterventionRepository()

    def determine_level(self, failure_risk: float) -> int:
        """
        Maps failure risk percentage to intervention level.
        This is the core decision engine for the Adaptive Intervention Ladder.
        """
        if failure_risk < 30:
            return 0
        elif failure_risk < 50:
            return 1
        elif failure_risk < 65:
            return 2
        elif failure_risk < 80:
            return 3
        elif failure_risk < 90:
            return 4
        else:
            return 5

    def get_intervention_type(self, level: int) -> str:
        """Maps intervention level to type string."""
        types = {
            0: "suggestion",
            1: "suggestion",
            2: "momentum",
            3: "collaboration",
            4: "critical",
            5: "recovery",
        }
        return types.get(level, "suggestion")

    def should_intervene(
        self,
        task: Task,
        failure_risk: float,
    ) -> bool:
        """
        Determines whether a new intervention should be created.
        Prevents intervention fatigue by checking recent intervention history.
        """
        new_level = self.determine_level(failure_risk)

        # Level 0 = monitoring only
        if new_level == 0:
            return False

        # Check recent interventions for this task
        recent = self._intervention_repo.list_by_task(task.id, resolved=False)

        # Don't create duplicate unresolved interventions at the same level
        if any(iv.level == new_level for iv in recent):
            return False

        # Always intervene at levels 4-5
        if new_level >= 4:
            return True

        # For levels 1-3, check if risk has increased since last intervention
        if recent:
            last_level = max(iv.level for iv in recent)
            if new_level > last_level:
                return True
            return False

        # No recent interventions — create one
        return True

    def create_intervention(
        self,
        task: Task,
        user_id: str,
        failure_risk: float,
        message: str,
        action_required: Optional[str] = None,
        trigger: str = "risk_threshold",
    ) -> Intervention:
        """
        Creates a new intervention record.
        Message and action are generated by the InterventionAgent in Phase 15.
        """
        level = self.determine_level(failure_risk)
        intervention_type = self.get_intervention_type(level)

        intervention = Intervention(
            taskId=task.id,
            userId=user_id,
            level=level,
            type=intervention_type,
            trigger=trigger,
            message=message,
            actionRequired=action_required,
        )

        created = self._intervention_repo.create_intervention(intervention)

        logger.info(
            "Intervention created",
            intervention_id=created.id,
            task_id=task.id,
            level=level,
            type=intervention_type,
        )

        return created

    def resolve_intervention(
        self,
        task_id: str,
        intervention_id: str,
        outcome: str,
    ) -> None:
        """
        Resolves an intervention with the user's response.
        Valid outcomes: accepted, dismissed, completed, ignored.
        """
        valid_outcomes = {"accepted", "dismissed", "completed", "ignored"}
        if outcome not in valid_outcomes:
            from app.core.exceptions import ValidationError
            raise ValidationError(f"Outcome must be one of: {valid_outcomes}")

        self._intervention_repo.resolve_intervention(
            task_id=task_id,
            intervention_id=intervention_id,
            outcome=outcome,
        )

        logger.info(
            "Intervention resolved",
            intervention_id=intervention_id,
            outcome=outcome,
        )

    def list_active_interventions(
        self,
        task_id: str,
    ) -> list[Intervention]:
        """Returns all unresolved interventions for a task."""
        return self._intervention_repo.list_by_task(task_id, resolved=False)

    def list_task_interventions(
        self,
        task_id: str,
    ) -> list[Intervention]:
        """Returns all interventions (active and resolved) for a task."""
        return self._intervention_repo.list_by_task(task_id)